version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-tfg
    ports:
      - "5672:5672"   # Puerto para la comunicación con tu backend NodeJS
      - "15672:15672" # Puerto para la interfaz gráfica de administración de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest