services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-tfg
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  api-gateway:
    build: ./backend/api-gateway
    container_name: gateway-tfg
    restart: on-failure
    ports:
      - "3000:3000"
    env_file:
      - ./backend/api-gateway/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-microservicio:
    build: ./backend/microservicio
    container_name: worker-tfg
    restart: on-failure
    env_file:
      - ./backend/microservicio/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
