version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-tfg
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./backend/api-gateway
    container_name: gateway-tfg
    restart: on-failure # <-- NUEVA LÍNEA
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-microservicio:
    build: ./backend/microservicio
    container_name: worker-tfg
    restart: on-failure # <-- NUEVA LÍNEA
    depends_on:
      rabbitmq:
        condition: service_healthy